from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor

def markdown_to_ppt(markdown_text, output_path):
    prs = Presentation()
    
    # Define standard slide layouts
    title_slide_layout = prs.slide_layouts[0]  # Title Slide
    bullet_slide_layout = prs.slide_layouts[1]  # Title & Content

    lines = markdown_text.splitlines()
    
    # --- Cover Slide ---
    title_text = lines[0].replace("# ", "").strip()
    subtitle_text = lines[2].strip() if len(lines) > 2 else "Generated by AI Task Automator"

    cover_slide = prs.slides.add_slide(title_slide_layout)
    cover_slide.shapes.title.text = title_text
    cover_slide.placeholders[1].text = subtitle_text

    # Style Cover Slide
    cover_slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(40)
    cover_slide.placeholders[1].text_frame.paragraphs[0].font.size = Pt(24)
    cover_slide.background.fill.solid()
    cover_slide.background.fill.fore_color.rgb = RGBColor(240, 240, 255)  # light bluish

    # --- Content Slides ---
    current_slide = None

    for line in lines[1:]:
        line = line.strip()
        if line.startswith("## "):
            title = line.replace("## ", "")
            current_slide = prs.slides.add_slide(bullet_slide_layout)
            current_slide.shapes.title.text = title
            content = current_slide.placeholders[1]
            content.text = ""  # reset
        elif line.startswith("- ") or line.startswith("* "):
            if current_slide:
                p = current_slide.placeholders[1].text_frame.add_paragraph()
                p.text = line[2:].strip()
                p.level = 0
                p.font.size = Pt(18)
        elif line == "":
            continue

    # Save to file
    prs.save(output_path)
